# Generated by Django 4.0.4 on 2022-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_height', models.IntegerField()),
                ('originally_uploaded_file', models.BooleanField()),
                ('expiring_link', models.IntegerField(null=True)),
            ],
        ),
    ]
