# Generated by Django 4.0.4 on 2022-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='generated_url',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
